version: '3'

services:
    neo4j:
      image: neo4j:4.3.0-enterprise
      environment:
        - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
        - NEO4J_dbms_memory_pagecache_size=${NEO4J_PAGECACHE}
        - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_INITIAL}
        - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MAX}
        - NEO4J_dbms_allow__upgrade=true
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      volumes:
        - ${NEO4J_DATA_VOLUME:-neo4j-data-volume}:/data
        - ${NEO4J_LOGS_VOLUME:-neo4j-logs-volume}:/logs
        - ${NEO4J_IMPORT_VOLUME:-neo4j-import-volume}:/var/lib/neo4j/import
        - ${NEO4J_PLUGINS_VOLUME:-neo4j-plugins-volume}:/plugins
        - ${NEO4J_BACKUPS_VOLUME:-neo4j-backups-volume}:/backups
      ports:
        - 7687:7687
        - 7474:7474
        - 7473:7473

volumes:
    neo4j-data-volume:
    neo4j-logs-volume:
    neo4j-import-volume:
    neo4j-plugins-volume:
    neo4j-backups-volume:
